export const INCREMENT="INCREMENT";
export const DECREMENT="DECREMENT";
export const CHANGE_THEME="CHANGE_THEME";
export const DISABLE_BUTTON="DISABLE_BUTTON";
export const ENABLED_BUTTON="ENABLED_BUTTON";